# Generated by Django 4.0.5 on 2022-07-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_inventory_quantitiy_product_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
